services:
  postgres:
    image: postgres:16-alpine
    container_name: myshop_postgres
    environment:
      POSTGRES_USER: myshopuser
      POSTGRES_PASSWORD: myshoppassword
      POSTGRES_DB: myshopdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
